### ISSUE TITLE
Configuring time and memory constraints when running NEvoPy programs

### ISSUE THREAD

**Issue by aaronatp** [Talendar/nevopy#14]
Hey @Talendar, this isn't exactly an issue but I couldn't quite find your email and I didn't know where else to submit this question, so apologies if it shouldn't be written here. To get a sense of how NEvoPy scripts can be configured, I'd like to run one of the examples (the XOR fixed topology example) you've given on a computing cluster I have access to. Can you give me a sense of how much memory and time I should request for the run, and if the example could/should be run with GPUs? (I have a sense that they can because the XOR fixed topology example seems to use Tensorflow layers, or at least wrappers of Tensorflow layers, which I believe can use GPUs.) Also, for a more complex neural network than the one in the example, is there a good way of estimating how much memory and time the runs will take?

**Comment by Talendar** [comment]
Hello, @Aaronpresser! Thank you for taking an interest in NEvoPy.

About estimating the time and computing resources of an experiment: it's really hard to say. Your hardware, the size and complexity of your neural networks and the experiment's environment (e.g., guessing the XOR function or playing a game) all have a huge impact on processing time and memory usage. The best way  I can think of to estimate these values is empirically. Run the algorithm for 1 generation and see how long it takes and how much memory is used. Depending on your environment, these values will remain somewhat stable throughout the experiment (this certainly applies to the experiment with the XOR function).

About using GPUs: it's possible to use them with the fixed topology algorithm and Tensorflow. The example with the XOR function uses a GPU, if available. Again, the only way I can think of to see if a GPU is worth using is empirically. Generally, though, if the fitness function only performs simple calculations that don't gain much from parallelization, using a GPU can actually be slower, because the overhead is greater than the performance gains. This is the case in the experiment with the XOR function when the number of variables is low.

You can take a look at the implementation of the [`RayProcessingScheduler`](https://github.com/Talendar/nevopy/blob/706b3356c43d9b71ba06e478bc5135e400a8c028/nevopy/processing/ray_processing.py#L42) to get a sense of how the workload is distributed to the GPU. It certainly needs improvement. The whole implementation of the fixed topology neuroevolution algorithm needs revision, actually. I plan to work on it as soon as my schedule allows.

Feel free to post bellow any remaining doubts!

**Comment by aaronatp** [comment]
Thank you @Talendar I really appreciate your response! Running it with only one generation sounds like a very reasonable thing to do and I think I will do that, and from what you're saying about the drawbacks of GPUs, I will consider using a CPU instead. In addition, thank you for telling me about the '''RayProcessingScheduler''' I will look into that.

Also, I've had some trouble running the '''xor_fixed_topology.py''' example. I created a new virtual environment with conda (version 4.3.0) and Python (version 3.6.0) and installed '''nevopy''' by cloning it into my system (with '''git clone https://github.com/Talendar/nevopy.git'''). After that, I ran the setup.py script which worked well, and then I moved to the example files and tried to run '''xor_fixed_topology.py''' with '''python xor_fixed_topology.py'''. This returned the following error unfortunately:

'''
2021-10-06 20:23:12.905105: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
/home/atp9753/.local/lib/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (2.3.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "xor_fixed_topology.py", line 10, in <module>
    import nevopy as ne
  File "/home/atp9753/.local/lib/python3.6/site-packages/nevopy/__init__.py", line 32, in <module>
    from nevopy import fixed_topology
  File "/home/atp9753/.local/lib/python3.6/site-packages/nevopy/fixed_topology/__init__.py", line 28, in <module>
    from nevopy.fixed_topology import layers
  File "/home/atp9753/.local/lib/python3.6/site-packages/nevopy/fixed_topology/layers/__init__.py", line 36, in <module>
    from nevopy.fixed_topology.layers.tf_layers import TensorFlowLayer
  File "/home/atp9753/.local/lib/python3.6/site-packages/nevopy/fixed_topology/layers/tf_layers.py", line 34, in <module>
    import tensorflow as tf
  File "/home/atp9753/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/atp9753/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import keras
  File "/home/atp9753/.local/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "/home/atp9753/.local/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 27, in <module>
    from tensorflow.python.keras.engine import sequential
  File "/home/atp9753/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 28, in <module>
    from tensorflow.python.keras import layers as layer_module
  File "/home/atp9753/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/__init__.py", line 177, in <module>
    from tensorflow.python.keras.layers.normalization import LayerNormalization
ImportError: cannot import name 'LayerNormalization'
'''

I was getting the same ImportError message about '''LayerNormalization''' before when I was trying to installing '''nevopy''' with pip, and also the same messages about '''libcudart.so.11.10''' which I wasn't able to resolve. I was wondering if you might be able to point me in the right direction towards resolving these issues? Thank you again for all your help, '''nevopy''' seems like a really exciting program and I'm really looking forward to using it!

**Comment by Talendar** [comment]
@Aaronpresser, I was unable to reproduce the error. I ran the code on both my machine and Google Colab (check the notebook [here](https://colab.research.google.com/drive/1NusNCWitNEho2qVt_nsGtOVNsL4EN9fR)).

There seems to be some sort of incompatibility between the Tensorflow's version that NEvoPy uses and the CUDA version you've installed. You could try installing a newer version of Tensorflow and see if it works.

**Comment by aaronatp** [comment]
@Talendar Thank you for your efforts and for pointing me towards that Colab - I have figured out the issue. I think it was an issue with my virtual environment. Thanks again!

**Comment by Talendar** [comment]
No problem, @Aaronpresser!
